name: Build Optimized Release APK

on:
  workflow_dispatch:
  push:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Java Environment
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Make Gradle Executable
        run: chmod +x ./gradlew

      - name: Compile Release APK (Optimized)
        run: ./gradlew assembleRelease

      - name: Upload Finished APK
        uses: actions/upload-artifact@v4
        with:
          name: MDGram-Release-APK
          path: '**/build/outputs/apk/**/*.apk'
          
